# Generated by Django 5.2.6 on 2025-12-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='leader',
            name='is_cabinet',
            field=models.BooleanField(default=True, help_text='Check if this leader is part of the main cabinet'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary General', 'Secretary General'), ('Deputy Secretary General', 'Deputy Secretary General'), ('Treasurer', 'Treasurer'), ('Minister', 'Minister'), ('Deputy Minister', 'Deputy Minister'), ('Director', 'Director'), ('Other', 'Other')], max_length=255),
        ),
    ]
