# Generated by Django 5.2.6 on 2025-09-19 06:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=users.models.get_current_date),
        ),
    ]
